name: 构建并发布 Docker 镜像

on:
  push:
    branches:
      - main  # 当推送到主分支时触发
  pull_request:
    branches:
      - main  # 当有 pull request 合并到主分支时触发
  workflow_dispatch:  # 手动触发

jobs:
  build:
    runs-on: ubuntu-22.04  # 指定使用 Ubuntu 22.04

    steps:
      # 步骤 1: 检出代码
      - name: 检出代码
        uses: actions/checkout@v3

      # 步骤 2: 设置日期标签
      - name: 设置日期标签
        id: date_tag
        run: echo "::set-output name=date::$(date +'%m%d-%H%M')"

      # 步骤 3: 使用 Docker PAT 登录 Docker Hub
      - name: 使用 Docker PAT 登录 Docker Hub
        run: echo "${{ secrets.DOCKER_PAT }}" | docker login -u "298977887" --password-stdin

      # 步骤 4: 构建 Docker 镜像
      - name: 构建 Docker 镜像
        run: docker build -t "298977887/openwrt-builder:latest" .

      # 步骤 5: 使用格式化标签（带日期和时间）
      - name: 使用格式化标签标记镜像
        run: |
          docker tag "298977887/openwrt-builder:latest" "298977887/openwrt-builder:2204-${DATE_TAG}"

      # 步骤 6: 推送镜像到 Docker Hub
      - name: 推送镜像到 Docker Hub
        run: |
          docker push "298977887/openwrt-builder:latest"
          docker push "298977887/openwrt-builder:2204-${DATE_TAG}"
