name: 构建并发布 Docker 镜像

on:
  push:
    branches:
      - main  # 当推送到主分支时触发
  pull_request:
    branches:
      - main  # 当有 pull request 合并到主分支时触发
  workflow_dispatch:  # 手动触发

jobs:
  build:
    runs-on: ubuntu-22.04  # 指定使用 Ubuntu 22.04

    steps:
      # Step 1: 检出代码
      - name: Check out the repository
        uses: actions/checkout@v3

      # Step 2: 使用 Docker PAT 登录 Docker Hub
      - name: Log in to Docker Hub using PAT
        run: echo "${{ secrets.DOCKER_PAT }}" | docker login -u "298977887" --password-stdin

      # Step 3: 构建 Docker 镜像
      - name: Build Docker Image
        run: docker build -t "298977887/openwrt-builder:latest" .

      # Step 4: 使用格式化标签（带日期和时间）
      - name: Tag Docker Image with Version
        run: |
          DATE_TAG=$(date +'%m%d-%H%M')         # 获取日期和时间（格式：1025-2310）
          docker tag "298977887/openwrt-builder:latest" "298977887/openwrt-builder:2204-${DATE_TAG}"

      # Step 5: 推送镜像到 Docker Hub
      - name: Push Docker Image to Docker Hub
        run: |
          docker push "298977887/openwrt-builder:latest"
          docker push "298977887/openwrt-builder:2204-${DATE_TAG}"